services:
  backend:
    build: ../RateMyProfessor
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rate_my_professor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: super duper password no one would guess
    networks:
      - rate-my-professor

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rate_my_professor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super duper password no one would guess
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rate-my-professor

  frontend:
    build: ../RateMyProfUI
    ports:
      - "3000:3000"
    networks:
      - rate-my-professor

networks:
  rate-my-professor:

volumes:
  postgres_data:
